routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    DashboardController,
    ProfileController,
    OrganizationController,
    StatmentController,
    TaskController,
    UserController,
};
use App\Http\Controllers\CommonController;
use App\Http\Controllers\Front\Auth\AuthenticatedSessionController as AuthAuthenticatedSessionController;
use App\Http\Controllers\Front\DonateController;
use App\Http\Controllers\Front\HomeController;
use App\Http\Controllers\Front\LoginController;
use App\Http\Controllers\Front\ProfileCOntroller as FrontProfileCOntroller;
use App\Http\Controllers\PANVerificationController;
use App\Http\Controllers\VerificationController;
use App\MsgApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[HomeController::class,'index'])->name('home');
Route::get('/about',[HomeController::class,'about'])->name('about');
Route::get('/term-condition',[HomeController::class,'termCondition'])->name('term-condition');
Route::get('/privacy-policy',[HomeController::class,'privacyPolicy'])->name('privacy-policy');
Route::get('/contact',[HomeController::class,'contact'])->name('contact');
Route::get('/donate-step-1',[HomeController::class,'donatate_step_one'])->name('donatate_step_one');
Route::get('/donate-step-2',[HomeController::class,'donatate_step_two'])->name('donatate_step_two');
Route::get('/donate-step-3',[HomeController::class,'donatate_step_three'])->name('donatate_step_three');
Route::get('/account-verify',[HomeController::class,'account_verify'])->name('account-verify');
Route::get('/bank-verify',[HomeController::class,'bank_verify'])->name('bank-verify');
Route::get('/registration',[HomeController::class,'option'])->name('option');
Route::get('/user-register',[HomeController::class,'userRegister'])->name('user-register');
Route::post('/user-registeration',[HomeController::class,'userRegisteration'])->name('userRegister');
Route::get('/account-verify/{id}',[HomeController::class,'account_verify'])->name('account-verify');
Route::get('/bank-verify/{id}',[HomeController::class,'bank_verify'])->name('bank-verify');
Route::get('/register', [LoginController::class, 'register'])->name('register');
Route::post('/sign-up', [LoginController::class, 'register_save'])->name('sign-up.stosre');
Route::post('/saveAccountData', [LoginController::class, 'saveAccountData'])->name('account-data');
Route::post('/bank-data', [LoginController::class, 'bankData'])->name('bank-data');
Route::get('/user/login', [LoginController::class, 'login'])->name('userlogin');
Route::get('/organization/login', [LoginController::class, 'organizationlogin'])->name('organizationLogin');
Route::get('/login', [LoginController::class, 'loginPage'])->name('login');
// Route::post('/signin', [LoginController::class, 'login_post'])->name('signin');
Route::post('/donate', [DonateController::class, 'donate'])->name('donate');
Route::get('/donate/{id}', [DonateController::class, 'donateUPdate']);
Route::post('/donate-update/{id}', [DonateController::class, 'donateUPdateData']);
Route::get('/donates/{id}', [DonateController::class, 'donateStepThree']);
Route::post('/donates-save/{id}', [DonateController::class, 'donateSave']);
Route::post('/thank-you/{id}', [DonateController::class, 'thankYou'])->name('thankYou');
Route::post('razorpay-payment',[DonateController::class,'store'])->name('razorpay.payment.store');

Route::post('/verify-pan', [PANVerificationController::class,'verify']);
Route::post('/verify-aadhar', [VerificationController::class,'aadhar']);
Route::post('/verify-o_aadhar', [VerificationController::class,'o_aadhar'])->name('verify.o_aadhar');
Route::post('/verify-o_email', [VerificationController::class,'verifyOemail'])->name('verify.o_email');
Route::post('/verifyOtp', [VerificationController::class,'verifyOtp'])->name('verifyOtp');
Route::post('/verify-opan', [PANVerificationController::class,'verifyopan'])->name('verify_opan');
Route::post('/verify-gstin', [PANVerificationController::class,'verifygstin'])->name('verify.gstin');
Route::post('/verify-cin', [PANVerificationController::class,'verifycin'])->name('verify.cin');
Route::post('/verify-account', [PANVerificationController::class,'verifyAcount'])->name('verify.account');
Route::post('/organization-data', [LoginController::class,'register_save'])->name('organization-data');
Route::post('/admin-login', [UserController::class, 'login_post'])->name('dashboard.login');

require __DIR__.'/auth.php';
Route::get('/dash',[HomeController::class,'dash'])->name('dash');
Route::namespace('App\Http\Controllers\Admin')->name('admin.')->prefix('admin')->middleware(['auth'])->group(function(){
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');
        Route::resource('users','UserController');
        Route::resource('organizationCat','OrganizaionCatController');
        Route::resource('organizations','OrganizationController');
        Route::resource('transaction','TransactionController');
        Route::resource('statements','StatmentController');
        Route::resource('newsletter','NewsLetterController');
        Route::resource('account','AccountsController');
        Route::resource('task','TaskController');
        Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');
        Route::post('/report/store', [StatmentController::class, 'store'])->name('report.store');
        Route::post('/month-report/store', [StatmentController::class, 'monthWise'])->name('monthreport.store');
        Route::post('/year-report/store', [StatmentController::class, 'yealyhWise'])->name('yearreport.store');
        Route::get('/report/request/{date}',[StatmentController::class, 'view'])->name('report.view');
        Route::get('/monthly-report/{month}',[StatmentController::class, 'monthlyview'])->name('report.monthlyview');
        Route::get('/year-report/{year}',[StatmentController::class, 'yearlyview'])->name('report.yearlyview');
        Route::post('/export', [StatmentController::class, 'export'])->name('datewise.export');
        Route::post('/monthWise', [StatmentController::class, 'monthWisePdf'])->name('monthWise');
        Route::post('/yearreportPdf', [StatmentController::class, 'yearreportPdf'])->name('yearreport');
        Route::get('/approve/{id}',[OrganizationController::class,'approve'])->name('organizations.approve');
        Route::get('/reject/{id}',[OrganizationController::class,'reject'])->name('organizations.reject');
        Route::get('/print/{id}',[OrganizationController::class,'print'])->name('organizations.print');
        Route::get('/printAll',[OrganizationController::class,'printAll'])->name('organizationCat.printAll');
        Route::get('/Suspend/{id}',[OrganizationController::class,'Suspend'])->name('organizations.Suspend');
        Route::get('/task/status/{id}',[TaskController::class,'updateStatus'])->name('task.status');
        Route::get('/profile',[ProfileController::class,'index'])->name('profile');
        Route::put('/profile-update',[ProfileController::class,'update'])->name('profile.update');   
        Route::get('logout', [AuthAuthenticatedSessionController::class, 'logout'])->name('admin.logout');

});
       

Route::prefix('user')->middleware('auth:donator')->group(function () {
    Route::get('/logout', [LoginController::class, 'logout'])->name('userlogout');
        Route::get('/dashboard',[HomeController::class,'dashboard'])->name('user-dashboard');
        Route::get('/donation-reciept/{id}', [VerificationController::class, 'donationReciept'])->name('donation.reciept');
    });


Route::prefix('organization')->middleware('auth:organiser')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'organizationDashboard'])->name('organizationDashboard');
    Route::get('/logout', [LoginController::class, 'logout'])->name('organizationogout');
});

Route::post('/get-data', [CommonController::class,'getData'])->name('get.data');
Route::post('/verify-mobilOtp', [VerificationController::class, 'mobileLogin'])->name('mobile.verity');
Route::post('/verifymobileOtp', [VerificationController::class, 'verifymobileOtp'])->name('verifymobileOtp');
Route::post('/userloginmobileOtp', [VerificationController::class, 'userloginmobileOtp'])->name('userloginmobileOtp');
Route::post('/verify-mobileotpLogin', [VerificationController::class, 'mobileotpLogin'])->name('mobileloginverify');
Route::post('/loginmobileOtp', [VerificationController::class, 'loginmobileOtp'])->name('loginmobileOtp');
Route::post('/verify-mobileotpLoginn', [VerificationController::class, 'usermobileotpLogin'])->name('usermobileotpLogin.verify');

Route::post('/subscribe', [HomeController::class,'subscribe'])->name('newsletter.subscribe');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;


    public static function saveData($dataVal, $fileName, $id = null)
    {
        $saveData = ($id) ? Task::find($id) : new Task;
        $saveData->content = $dataVal->content;
        if($fileName):
            $saveData->file = $fileName;
        endif;
        $saveData->save();
        return $saveData;
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Task;
use App\MsgApp;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\File;

class TaskController extends Controller
{
   
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Task::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('file', function ($submission) {
                    $fileUrl = asset($submission->file);
                    return '<a href="' . $fileUrl . '" target="_blank"><img src="' . asset('assets/pdf.png') . '" alt="PDF" style="width: 50px; height: 50px;"></a>';
                })
                ->editColumn('status', function ($row) {
                    if($row->status != 'Completed')
                    {
                        return btnStatus(route('admin.task.status', $row->id));
                    }
                    else{
                        return 'Completed';
                    }
                   
                })
                
                ->addColumn('action', function ($row) {
                   
                    $editUrl = route('admin.task.edit', $row->id);
                    $deleteUrl = route('admin.task.destroy', $row->id);
                    $btn = '';
                    if (auth()->user()->can('Task edit', $row)) {
                        $btn .= btnEdit($editUrl);
                    }
                    if (auth()->user()->can('Task delete', $row)) {
                        $btn .= btnDelete($deleteUrl);
                    }
                    return $btn;
                })
                ->rawColumns(['action','file','status'])
                ->make(true);
        }
        
        return view('admin.task.index');
    }

    public function create()
    {
        return view('admin.task.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'file' => 'required|file|mimes:pdf',
            ],
            [
                'required' => ':attribute is required.',
                'regex' => ':attribute is invalid.',
            ],
            ['file' => 'File']
        );
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput($request->all());
        }
        $file = (new \App\Http\Controllers\CommonController)->uploadFile($request, 'file', '/task');
        Task::saveData($request, $file);
        return redirect('/admin/task')->with('success', MsgApp::SUCCESS_ADDED);
    }

    public function show($id)
    {
        $data = Task::where('id', $id)->first();
        if (File::exists(public_path($data->file))) {
            File::delete(public_path($data->file));
        }
        $data->delete();
        return redirect('/admin/task')->with('success', MsgApp::SUCCESS_DEL);
    }

    public function edit($id)
    {
        $data = Task::find($id);
        return view('admin.task.edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $data = Task::find($id);
        if (File::exists(public_path($data->file))) {
            File::delete(public_path($data->file));
        }
        $file = (new \App\Http\Controllers\CommonController)->uploadFile($request, 'file', '/task');
        Task::saveData($request, $file, $id);
        return redirect('/admin/task')->with('success', MsgApp::SUCCESS_UPD);
    }

    public function updateStatus($id)
    {
        Task::where('id', $id)->update(['status' => 'Completed']);
        
        return redirect()->back()->with('success', 'Status UPdate successfully');
    }

    public function destroy($id)
    {
        return $id;
    }
}

resources/views/admin/task/create.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')
<div class="subheader py-2 py-lg-4  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-2">

                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">
                       Create Task </h5>
                    <!--end::Page Title-->

                    <!--begin::Actions-->
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                    
                    <!--end::Actions-->
                </div>
                <!--end::Info-->


            </div>
        </div>
<!--begin::Entry-->
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class=" container card-fixed-align">
        <!--begin::Card-->
        @if(session('success'))
        <div class="alert alert-custom alert-success fade show" role="alert">
            <div class="alert-icon"><i class="flaticon2-check-mark"></i></div>
            <div class="alert-text">{{ session('success')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif
        @if(session('failed'))
        <div class="alert alert-custom alert-danger fade show" role="alert">
            <div class="alert-icon"><i class="flaticon-warning"></i></div>
            <div class="alert-text">{{ session('failed')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif

        <div class="card card-custom">
            <!--begin::Form-->
            <form action="{{route('admin.task.store')}}" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_token" id="csrf_token" value="{{ Session::token() }}" />
                <div class="card-body">


                    <div class="row">
                        <div class="col-md-12">
                            <label class="col-form-label" for="name">Description</label>
                            <div>
                            <textarea class="ckeditor form-control" rows="3" name="content" placeholder="Description"
                            id="description">{{ old('content') }}</textarea>
                            
                            @if($errors->has('content'))
                               <div class="invalid-feedback">{{ $errors->first('content') }}</div>
                               @enderror
                            </div>
                        </div>
                        
                       
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-12">
                                    <label class="col-form-label" for="image">File</label><br>
                                </div>
                                <div class="col-12">
                                    <div>
                                        <input type="file" class="custom-file-input" name="file" />
                                        <label class="custom-file-label" for="image">Choose file</label>
                                        @if($errors->has('file'))
                                        <div class="invalid-feedback">{{ $errors->first('file') }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mt-4">
                    <div class="row">
                        <div class="col-12 d-flex justify-content-end">
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                            <a href="{{route('admin.task.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </div>
                </div>
            </form>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
</div>
<!--end::Content-->
@endsection

resources/views/admin/task/edit.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')
<div class="subheader py-2 py-lg-4  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-2">

                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">
                       Update Task </h5>
                    <!--end::Page Title-->

                    <!--begin::Actions-->
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                    
                    <!--end::Actions-->
                </div>
                <!--end::Info-->


            </div>
        </div>
<!--begin::Entry-->
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class=" container card-fixed-align">
        <!--begin::Card-->
        @if(session('success'))
        <div class="alert alert-custom alert-success fade show" role="alert">
            <div class="alert-icon"><i class="flaticon2-check-mark"></i></div>
            <div class="alert-text">{{ session('success')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif
        @if(session('failed'))
        <div class="alert alert-custom alert-danger fade show" role="alert">
            <div class="alert-icon"><i class="flaticon-warning"></i></div>
            <div class="alert-text">{{ session('failed')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif

        <div class="card card-custom">
            <!--begin::Form-->
            <form action="{{route('admin.task.update', $data->id)}}" method="post" enctype="multipart/form-data">
            @method('PATCH')
                <input type="hidden" name="_token" id="csrf_token" value="{{ Session::token() }}" />
                <div class="card-body">


                    <div class="row">
                        <div class="col-md-12">
                            <label class="col-form-label" for="name">Description</label>
                            <div>
                            <textarea class="ckeditor form-control" rows="3" name="content" placeholder="Description"
                            id="description">@if(old('content')){{ old('content') }}@else{{ $data->content }}@endif </textarea>
                            
                            @if($errors->has('content'))
                               <div class="invalid-feedback">{{ $errors->first('content') }}</div>
                               @enderror
                            </div>
                        </div>
                        
                       
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-12">
                                    <label class="col-form-label" for="image">File</label><br>
                                </div>
                                <div class="col-12">
                                    <div>
                                        <input type="file" class="custom-file-input" name="file" />
                                        <label class="custom-file-label" for="image">Choose file</label>
                                        @if($errors->has('file'))
                                        <div class="invalid-feedback">{{ $errors->first('file') }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mt-4">
                    <div class="row">
                        <div class="col-12 d-flex justify-content-end">
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                            <a href="{{route('admin.task.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </div>
                </div>
            </form>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
</div>
<!--end::Content-->
@endsection

resources/views/admin/task/index.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')
<!--begin::Entry-->
<div class="subheader py-2 py-lg-4  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-2">

                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">
                        Task List </h5>
                    <!--end::Page Title-->

                    <!--begin::Actions-->
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                    @can('Task create')
                    <a href="{{route('admin.task.create')}}" class="btn btn-light-warning font-weight-bolder btn-sm">
                        Add New
                    </a>
                    @endcan
                    <!--end::Actions-->
                </div>
                <!--end::Info-->


            </div>
        </div>
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class=" container card-fixed-align">
        <!--begin::Card-->
        <div class="card card-custom">
            <div class="card-body">
                <!--begin: Datatable-->
                <table class="table table-bordered task-dataTable">
                    <thead>
                        <tr>
                            <th>File</th>
                            <th>Content</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <!--end: Datatable-->
            </div>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
</div>
<!--end::Content-->
@endsection