routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    DashboardController,
    ProfileController,
    OrganizationController,
    StatmentController,
    TaskController,
    UserController,
};
use App\Http\Controllers\CommonController;
use App\Http\Controllers\Front\Auth\AuthenticatedSessionController as AuthAuthenticatedSessionController;
use App\Http\Controllers\Front\DonateController;
use App\Http\Controllers\Front\HomeController;
use App\Http\Controllers\Front\LoginController;
use App\Http\Controllers\Front\ProfileCOntroller as FrontProfileCOntroller;
use App\Http\Controllers\PANVerificationController;
use App\Http\Controllers\VerificationController;
use App\MsgApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[HomeController::class,'index'])->name('home');
Route::get('/about',[HomeController::class,'about'])->name('about');
Route::get('/term-condition',[HomeController::class,'termCondition'])->name('term-condition');
Route::get('/privacy-policy',[HomeController::class,'privacyPolicy'])->name('privacy-policy');
Route::get('/contact',[HomeController::class,'contact'])->name('contact');
Route::get('/donate-step-1',[HomeController::class,'donatate_step_one'])->name('donatate_step_one');
Route::get('/donate-step-2',[HomeController::class,'donatate_step_two'])->name('donatate_step_two');
Route::get('/donate-step-3',[HomeController::class,'donatate_step_three'])->name('donatate_step_three');
Route::get('/account-verify',[HomeController::class,'account_verify'])->name('account-verify');
Route::get('/bank-verify',[HomeController::class,'bank_verify'])->name('bank-verify');
Route::get('/registration',[HomeController::class,'option'])->name('option');
Route::get('/user-register',[HomeController::class,'userRegister'])->name('user-register');
Route::post('/user-registeration',[HomeController::class,'userRegisteration'])->name('userRegister');
Route::get('/account-verify/{id}',[HomeController::class,'account_verify'])->name('account-verify');
Route::get('/bank-verify/{id}',[HomeController::class,'bank_verify'])->name('bank-verify');
Route::get('/register', [LoginController::class, 'register'])->name('register');
Route::post('/sign-up', [LoginController::class, 'register_save'])->name('sign-up.stosre');
Route::post('/saveAccountData', [LoginController::class, 'saveAccountData'])->name('account-data');
Route::post('/bank-data', [LoginController::class, 'bankData'])->name('bank-data');
Route::get('/user/login', [LoginController::class, 'login'])->name('userlogin');
Route::get('/organization/login', [LoginController::class, 'organizationlogin'])->name('organizationLogin');
Route::get('/login', [LoginController::class, 'loginPage'])->name('login');
// Route::post('/signin', [LoginController::class, 'login_post'])->name('signin');
Route::post('/donate', [DonateController::class, 'donate'])->name('donate');
Route::get('/donate/{id}', [DonateController::class, 'donateUPdate']);
Route::post('/donate-update/{id}', [DonateController::class, 'donateUPdateData']);
Route::get('/donates/{id}', [DonateController::class, 'donateStepThree']);
Route::post('/donates-save/{id}', [DonateController::class, 'donateSave']);
Route::post('/thank-you/{id}', [DonateController::class, 'thankYou'])->name('thankYou');
Route::post('razorpay-payment',[DonateController::class,'store'])->name('razorpay.payment.store');

Route::post('/verify-pan', [PANVerificationController::class,'verify']);
Route::post('/verify-aadhar', [VerificationController::class,'aadhar']);
Route::post('/verify-o_aadhar', [VerificationController::class,'o_aadhar'])->name('verify.o_aadhar');
Route::post('/verify-o_email', [VerificationController::class,'verifyOemail'])->name('verify.o_email');
Route::post('/verifyOtp', [VerificationController::class,'verifyOtp'])->name('verifyOtp');
Route::post('/verify-opan', [PANVerificationController::class,'verifyopan'])->name('verify_opan');
Route::post('/verify-gstin', [PANVerificationController::class,'verifygstin'])->name('verify.gstin');
Route::post('/verify-cin', [PANVerificationController::class,'verifycin'])->name('verify.cin');
Route::post('/verify-account', [PANVerificationController::class,'verifyAcount'])->name('verify.account');
Route::post('/organization-data', [LoginController::class,'register_save'])->name('organization-data');
Route::post('/admin-login', [UserController::class, 'login_post'])->name('dashboard.login');

require __DIR__.'/auth.php';
Route::get('/dash',[HomeController::class,'dash'])->name('dash');
Route::namespace('App\Http\Controllers\Admin')->name('admin.')->prefix('admin')->middleware(['auth'])->group(function(){
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');
        Route::resource('users','UserController');
        Route::resource('organizationCat','OrganizaionCatController');
        Route::resource('organizations','OrganizationController');
        Route::resource('transaction','TransactionController');
        Route::resource('statements','StatmentController');
        Route::resource('newsletter','NewsLetterController');
        Route::resource('account','AccountsController');
        Route::resource('task','TaskController');
        Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');
        Route::post('/report/store', [StatmentController::class, 'store'])->name('report.store');
        Route::post('/month-report/store', [StatmentController::class, 'monthWise'])->name('monthreport.store');
        Route::post('/year-report/store', [StatmentController::class, 'yealyhWise'])->name('yearreport.store');
        Route::get('/report/request/{date}',[StatmentController::class, 'view'])->name('report.view');
        Route::get('/monthly-report/{month}',[StatmentController::class, 'monthlyview'])->name('report.monthlyview');
        Route::get('/year-report/{year}',[StatmentController::class, 'yearlyview'])->name('report.yearlyview');
        Route::post('/export', [StatmentController::class, 'export'])->name('datewise.export');
        Route::post('/monthWise', [StatmentController::class, 'monthWisePdf'])->name('monthWise');
        Route::post('/yearreportPdf', [StatmentController::class, 'yearreportPdf'])->name('yearreport');
        Route::get('/approve/{id}',[OrganizationController::class,'approve'])->name('organizations.approve');
        Route::get('/reject/{id}',[OrganizationController::class,'reject'])->name('organizations.reject');
        Route::get('/print/{id}',[OrganizationController::class,'print'])->name('organizations.print');
        Route::get('/printAll',[OrganizationController::class,'printAll'])->name('organizationCat.printAll');
        Route::get('/Suspend/{id}',[OrganizationController::class,'Suspend'])->name('organizations.Suspend');
        Route::get('/task/status/{id}',[TaskController::class,'updateStatus'])->name('task.status');
        Route::get('/profile',[ProfileController::class,'index'])->name('profile');
        Route::put('/profile-update',[ProfileController::class,'update'])->name('profile.update');   
        Route::get('logout', [AuthAuthenticatedSessionController::class, 'logout'])->name('admin.logout');

});
       

Route::prefix('user')->middleware('auth:donator')->group(function () {
    Route::get('/logout', [LoginController::class, 'logout'])->name('userlogout');
        Route::get('/dashboard',[HomeController::class,'dashboard'])->name('user-dashboard');
        Route::get('/donation-reciept/{id}', [VerificationController::class, 'donationReciept'])->name('donation.reciept');
    });


Route::prefix('organization')->middleware('auth:organiser')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'organizationDashboard'])->name('organizationDashboard');
    Route::get('/logout', [LoginController::class, 'logout'])->name('organizationogout');
});

Route::post('/get-data', [CommonController::class,'getData'])->name('get.data');
Route::post('/verify-mobilOtp', [VerificationController::class, 'mobileLogin'])->name('mobile.verity');
Route::post('/verifymobileOtp', [VerificationController::class, 'verifymobileOtp'])->name('verifymobileOtp');
Route::post('/userloginmobileOtp', [VerificationController::class, 'userloginmobileOtp'])->name('userloginmobileOtp');
Route::post('/verify-mobileotpLogin', [VerificationController::class, 'mobileotpLogin'])->name('mobileloginverify');
Route::post('/loginmobileOtp', [VerificationController::class, 'loginmobileOtp'])->name('loginmobileOtp');
Route::post('/verify-mobileotpLoginn', [VerificationController::class, 'usermobileotpLogin'])->name('usermobileotpLogin.verify');

Route::post('/subscribe', [HomeController::class,'subscribe'])->name('newsletter.subscribe');

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\MsgApp;
use Illuminate\Http\Request;

use Spatie\Permission\Models\Permission;



class PermissionController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('role_or_permission:Permission access|Permission create|Permission edit|Permission delete', ['only' => ['index','show']]);
        $this->middleware('role_or_permission:Permission create', ['only' => ['create','store']]);
        $this->middleware('role_or_permission:Permission edit', ['only' => ['edit','update']]);
        $this->middleware('role_or_permission:Permission delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permission= Permission::latest()->get();

        return view('setting.permission.index',['permissions'=>$permission]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('setting.permission.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation 
        $request->validate([
            'name'=>'required',
        ]);
        $permission = Permission::create(['name'=>$request->name]);
        return redirect()->route('admin.permissions.index')->with('success', MsgApp::SUCCESS_ADDED);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Permission::where('id',$id)->delete();
        return redirect()->route('admin.permissions.index')->with('success', MsgApp::SUCCESS_DEL);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
       return view('setting.permission.edit',['permission' => $permission]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $permission->update(['name'=>$request->name]);
        return redirect()->route('admin.permissions.index')->with('success', MsgApp::SUCCESS_UPD);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id;
    }
}

resources/views/setting/permission/edit.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')
   <div>
        <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
            <div class="container mx-auto px-6 py-1">
              <div class="bg-white shadow-md rounded my-6 p-5">
                <form method="POST" action="{{ route('admin.permissions.update',$permission->id)}}">
                  @csrf
                  @method('put')
                  <div class="flex flex-col space-y-2">
                  <label for="role_name" class="text-gray-700 select-none font-medium">Permission Name</label>
                  <input
                    id="role_name"
                    type="text"
                    name="name"
                    value="{{ old('name',$permission->name) }}"
                    placeholder="Enter permission"
                    class="form-control"
                  />
                </div>
                <div class="text-center mt-16">
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                </div>
              </div>

             
            </div>
        </main>
    </div>
</div>
@endsection

resources/views/setting/permission/index.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')
<div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-4  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-2">

                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">
                    List</h5>
                    <!--end::Page Title-->
                    <!--begin::Actions-->
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                    @can('Permission create')
                    <a href="{{route('admin.permissions.create')}}" class="btn btn-light-warning font-weight-bolder btn-sm">
                        Add New
                    </a>
                    @endcan
                    <!--end::Actions-->
                </div>
                <!--end::Info-->
            </div>
        </div>
<!--begin::Entry-->
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class=" container ">
        @if(session('success'))
        <div class="alert alert-custom alert-success fade show" role="alert">
            <div class="alert-icon"><i class="flaticon2-check-mark"></i></div>
            <div class="alert-text">{{ session('success')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif
        @if(session('failed'))
        <div class="alert alert-custom alert-danger fade show" role="alert">
            <div class="alert-icon"><i class="flaticon-warning"></i></div>
            <div class="alert-text">{{ session('failed')}}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="ki ki-close"></i></span>
                </button>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col-sm-8">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-body">
                        <!--begin: Datatable-->
                        <table class="text-left w-full border-collapse">
                  <thead>
                    <tr>
                      <th class="py-4 px-6 bg-grey-lightest font-bold text-sm text-grey-dark border-b border-grey-light">Permission Name</th>
                      
                      <th class="py-4 px-6 bg-grey-lightest font-bold text-sm text-grey-dark border-b border-grey-light text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody>

                    @can('Permission access')
                      @foreach($permissions as $permission)
                      <tr class="hover:bg-grey-lighter">
                        <td class="py-4 px-6 border-b border-grey-light">{{ $permission->name }}</td>
                        <td class="py-4 px-6 border-b border-grey-light text-right">
                          @can('Permission edit')
                          <a class="btn btn-primary" href="{{route('admin.permissions.edit',$permission->id)}}">Edit</a>
                          @endcan

                          @can('Permission delete')
                          <a class="btn btn-danger" href="{{ route('admin.permissions.destroy', $permission->id) }}">Delete</a>
                          @endcan
                        </td>
                      </tr>
                      @endforeach
                    @endcan
                    
                  </tbody>
                </table>
                        <!--end: Datatable-->
                    </div>

                </div>
            </div>
        </div>

        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
</div>
<!--end::Content-->
@endsection

resources/views/setting/permission/new.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.aside')   <div>
        <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
            <div class="container mx-auto px-6 py-1">
              <div class="bg-white shadow-md rounded my-6 p-5">
                <form method="POST" action="{{ route('admin.permissions.store')}}">
                  @csrf
                  @method('post')
                <div class="flex flex-col space-y-2">
                  <label for="role_name" class="text-gray-700 select-none font-medium">Permission Name</label>
                  <input
                    id="role_name"
                    type="text"
                    name="name"
                    value="{{ old('name') }}"
                    placeholder="Enter permission"
                    class="form-control"
                  />
                </div>
                <div class="text-center mt-16">
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                              </div>
              </div>
            </div>
        </main>
    </div>
</div>
@endsection